# Generated by Django 5.1.3 on 2024-11-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shimlaattraction',
            name='image',
        ),
    ]
