# Generated by Django 5.1.3 on 2024-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shimlaattraction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shimlaattraction',
            name='image_url',
            field=models.URLField(default='https://image.com'),
        ),
        migrations.AlterField(
            model_name='shimlaattraction',
            name='image',
            field=models.ImageField(upload_to='attractions/'),
        ),
    ]
