# Generated by Django 5.1.3 on 2024-11-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shimlaattraction_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shimlaattraction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
