# Generated by Django 5.1.3 on 2024-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_shimlaattraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shimlaattraction',
            name='image',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
