# Generated by Django 5.1.3 on 2024-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_shimlaattraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shimlaattraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp/'),
        ),
    ]
