# Generated by Django 5.1.3 on 2025-03-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shimlaattraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shimlaattraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
