# Generated by Django 5.1.3 on 2025-03-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_shimlaattraction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shimlaattraction',
            name='image_url',
        ),
    ]
